// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleService;

namespace VehicleService.Migrations
{
    [DbContext(typeof(VehicleDBContext))]
    partial class VehicleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleService.VehicleMake", b =>
                {
                    b.Property<int>("VehicleMakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleMakeId");

                    b.ToTable("VehicleMakers");

                    b.HasData(
                        new
                        {
                            VehicleMakeId = 1,
                            Abrv = "BMW",
                            Name = "Bmw"
                        },
                        new
                        {
                            VehicleMakeId = 2,
                            Abrv = "JAG",
                            Name = "Jaguar"
                        },
                        new
                        {
                            VehicleMakeId = 3,
                            Abrv = "FRD",
                            Name = "Ford"
                        },
                        new
                        {
                            VehicleMakeId = 4,
                            Abrv = "NIS",
                            Name = "Nissan"
                        },
                        new
                        {
                            VehicleMakeId = 5,
                            Abrv = "VW",
                            Name = "VolksWagen"
                        });
                });

            modelBuilder.Entity("VehicleService.VehicleModel", b =>
                {
                    b.Property<int>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abrv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleMakeId")
                        .HasColumnType("int");

                    b.HasKey("VehicleModelId");

                    b.HasIndex("VehicleMakeId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            VehicleModelId = 1,
                            Abrv = "TO2",
                            Name = "Touareg2",
                            VehicleMakeId = 5
                        },
                        new
                        {
                            VehicleModelId = 2,
                            Abrv = "340",
                            Name = "340 Gran Turismo",
                            VehicleMakeId = 1
                        },
                        new
                        {
                            VehicleModelId = 3,
                            Abrv = "F15",
                            Name = "F-150",
                            VehicleMakeId = 3
                        },
                        new
                        {
                            VehicleModelId = 4,
                            Abrv = "XE",
                            Name = "XE",
                            VehicleMakeId = 2
                        },
                        new
                        {
                            VehicleModelId = 5,
                            Abrv = "GTR",
                            Name = "GT-R",
                            VehicleMakeId = 4
                        },
                        new
                        {
                            VehicleModelId = 6,
                            Abrv = "FCS",
                            Name = "Focus",
                            VehicleMakeId = 3
                        },
                        new
                        {
                            VehicleModelId = 7,
                            Abrv = "550",
                            Name = "M550",
                            VehicleMakeId = 1
                        },
                        new
                        {
                            VehicleModelId = 8,
                            Abrv = "GLI",
                            Name = "Jetta GLI",
                            VehicleMakeId = 5
                        },
                        new
                        {
                            VehicleModelId = 9,
                            Abrv = "350",
                            Name = "350Z",
                            VehicleMakeId = 4
                        },
                        new
                        {
                            VehicleModelId = 10,
                            Abrv = "IPC",
                            Name = "I-Pace",
                            VehicleMakeId = 2
                        },
                        new
                        {
                            VehicleModelId = 11,
                            Abrv = "FRN",
                            Name = "Frontier",
                            VehicleMakeId = 4
                        },
                        new
                        {
                            VehicleModelId = 12,
                            Abrv = "FTP",
                            Name = "F-Type Coupe",
                            VehicleMakeId = 2
                        },
                        new
                        {
                            VehicleModelId = 13,
                            Abrv = "MST",
                            Name = "Mustang",
                            VehicleMakeId = 3
                        },
                        new
                        {
                            VehicleModelId = 14,
                            Abrv = "ART",
                            Name = "Arteon",
                            VehicleMakeId = 5
                        },
                        new
                        {
                            VehicleModelId = 15,
                            Abrv = "228",
                            Name = "228 Gran Coupe",
                            VehicleMakeId = 1
                        });
                });

            modelBuilder.Entity("VehicleService.VehicleModel", b =>
                {
                    b.HasOne("VehicleService.VehicleMake", "VehicleMake")
                        .WithMany()
                        .HasForeignKey("VehicleMakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
